/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class AudioStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AudioStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_AudioStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSampleRate(long value) {
    RaylibJNI.AudioStream_sampleRate_set(swigCPtr, this, value);
  }

  public long getSampleRate() {
    return RaylibJNI.AudioStream_sampleRate_get(swigCPtr, this);
  }

  public void setSampleSize(long value) {
    RaylibJNI.AudioStream_sampleSize_set(swigCPtr, this, value);
  }

  public long getSampleSize() {
    return RaylibJNI.AudioStream_sampleSize_get(swigCPtr, this);
  }

  public void setChannels(long value) {
    RaylibJNI.AudioStream_channels_set(swigCPtr, this, value);
  }

  public long getChannels() {
    return RaylibJNI.AudioStream_channels_get(swigCPtr, this);
  }

  public void setAudioBuffer(SWIGTYPE_p_void value) {
    RaylibJNI.AudioStream_audioBuffer_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getAudioBuffer() {
    long cPtr = RaylibJNI.AudioStream_audioBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFormat(int value) {
    RaylibJNI.AudioStream_format_set(swigCPtr, this, value);
  }

  public int getFormat() {
    return RaylibJNI.AudioStream_format_get(swigCPtr, this);
  }

  public void setSource(long value) {
    RaylibJNI.AudioStream_source_set(swigCPtr, this, value);
  }

  public long getSource() {
    return RaylibJNI.AudioStream_source_get(swigCPtr, this);
  }

  public void setBuffers(SWIGTYPE_p_unsigned_int value) {
    RaylibJNI.AudioStream_buffers_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getBuffers() {
    long cPtr = RaylibJNI.AudioStream_buffers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public AudioStream() {
    this(RaylibJNI.new_AudioStream(), true);
  }

}
