/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Camera3D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Camera3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Camera3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Camera3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPosition(Vector3 value) {
    RaylibJNI.Camera3D_position_set(swigCPtr, this, Vector3.getCPtr(value), value);
  }

  public Vector3 getPosition() {
    long cPtr = RaylibJNI.Camera3D_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector3(cPtr, false);
  }

  public void setTarget(Vector3 value) {
    RaylibJNI.Camera3D_target_set(swigCPtr, this, Vector3.getCPtr(value), value);
  }

  public Vector3 getTarget() {
    long cPtr = RaylibJNI.Camera3D_target_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector3(cPtr, false);
  }

  public void setUp(Vector3 value) {
    RaylibJNI.Camera3D_up_set(swigCPtr, this, Vector3.getCPtr(value), value);
  }

  public Vector3 getUp() {
    long cPtr = RaylibJNI.Camera3D_up_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector3(cPtr, false);
  }

  public void setFovy(float value) {
    RaylibJNI.Camera3D_fovy_set(swigCPtr, this, value);
  }

  public float getFovy() {
    return RaylibJNI.Camera3D_fovy_get(swigCPtr, this);
  }

  public void setType(int value) {
    RaylibJNI.Camera3D_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return RaylibJNI.Camera3D_type_get(swigCPtr, this);
  }

  public Camera3D() {
    this(RaylibJNI.new_Camera3D(), true);
  }

}
