/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public final class CameraMode {
  public final static CameraMode CAMERA_CUSTOM = new CameraMode("CAMERA_CUSTOM", RaylibJNI.CAMERA_CUSTOM_get());
  public final static CameraMode CAMERA_FREE = new CameraMode("CAMERA_FREE");
  public final static CameraMode CAMERA_ORBITAL = new CameraMode("CAMERA_ORBITAL");
  public final static CameraMode CAMERA_FIRST_PERSON = new CameraMode("CAMERA_FIRST_PERSON");
  public final static CameraMode CAMERA_THIRD_PERSON = new CameraMode("CAMERA_THIRD_PERSON");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraMode.class + " with value " + swigValue);
  }

  private CameraMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraMode(String swigName, CameraMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraMode[] swigValues = { CAMERA_CUSTOM, CAMERA_FREE, CAMERA_ORBITAL, CAMERA_FIRST_PERSON, CAMERA_THIRD_PERSON };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

