/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Camera2D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Camera2D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Camera2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Camera2D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOffset(Vector2 value) {
    RaylibJNI.Camera2D_offset_set(swigCPtr, this, Vector2.getCPtr(value), value);
  }

  public Vector2 getOffset() {
    long cPtr = RaylibJNI.Camera2D_offset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector2(cPtr, false);
  }

  public void setTarget(Vector2 value) {
    RaylibJNI.Camera2D_target_set(swigCPtr, this, Vector2.getCPtr(value), value);
  }

  public Vector2 getTarget() {
    long cPtr = RaylibJNI.Camera2D_target_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector2(cPtr, false);
  }

  public void setRotation(float value) {
    RaylibJNI.Camera2D_rotation_set(swigCPtr, this, value);
  }

  public float getRotation() {
    return RaylibJNI.Camera2D_rotation_get(swigCPtr, this);
  }

  public void setZoom(float value) {
    RaylibJNI.Camera2D_zoom_set(swigCPtr, this, value);
  }

  public float getZoom() {
    return RaylibJNI.Camera2D_zoom_get(swigCPtr, this);
  }

  public Camera2D() {
    this(RaylibJNI.new_Camera2D(), true);
  }

}
