/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public final class CameraType {
  public final static CameraType CAMERA_PERSPECTIVE = new CameraType("CAMERA_PERSPECTIVE", RaylibJNI.CAMERA_PERSPECTIVE_get());
  public final static CameraType CAMERA_ORTHOGRAPHIC = new CameraType("CAMERA_ORTHOGRAPHIC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraType.class + " with value " + swigValue);
  }

  private CameraType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraType(String swigName, CameraType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraType[] swigValues = { CAMERA_PERSPECTIVE, CAMERA_ORTHOGRAPHIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

