/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Color {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    RaylibJNI.Color_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return RaylibJNI.Color_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    RaylibJNI.Color_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return RaylibJNI.Color_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    RaylibJNI.Color_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return RaylibJNI.Color_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    RaylibJNI.Color_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return RaylibJNI.Color_a_get(swigCPtr, this);
  }

  public Color() {
    this(RaylibJNI.new_Color(), true);
  }

  public Color(int r, int g, int b, int a) {
    this();
    this.setR((short)r);
    this.setG((short)g);
    this.setB((short)b);
    this.setA((short)a);
  }

  public Color(int r, int g, int b) {
    this(r, g, b, 255);
  }
  
  public static final Color LIGHTGRAY = new Color(200, 200, 200, 255 );
  public static final Color GRAY      = new Color(130, 130, 130, 255 );
  public static final Color DARKGRAY  = new Color(80, 80, 80, 255 );
  public static final Color YELLOW    = new Color(253, 249, 0, 255 );
  public static final Color GOLD      = new Color(255, 203, 0, 255 );
  public static final Color ORANGE    = new Color(255, 161, 0, 255 );
  public static final Color PINK      = new Color(255, 109, 194, 255 );
  public static final Color RED       = new Color(230, 41, 55, 255 );
  public static final Color MAROON    = new Color(190, 33, 55, 255 );
  public static final Color GREEN     = new Color(0, 228, 48, 255 );
  public static final Color LIME      = new Color(0, 158, 47, 255 );
  public static final Color DARKGREEN = new Color(0, 117, 44, 255 );
  public static final Color SKYBLUE   = new Color(102, 191, 255, 255 );
  public static final Color BLUE      = new Color(0, 121, 241, 255 );
  public static final Color DARKBLUE  = new Color(0, 82, 172, 255 );
  public static final Color PURPLE    = new Color(200, 122, 255, 255 );
  public static final Color VIOLET    = new Color(135, 60, 190, 255 );
  public static final Color DARKPURPLE= new Color(112, 31, 126, 255 );
  public static final Color BEIGE     = new Color(211, 176, 131, 255 );
  public static final Color BROWN     = new Color(127, 106, 79, 255 );
  public static final Color DARKBROWN = new Color(76, 63, 47, 255 );

  public static final Color WHITE     = new Color(255, 255, 255, 255 );
  public static final Color BLACK     = new Color(0, 0, 0, 255 );
  public static final Color BLANK     = new Color(0, 0, 0, 0 );
  public static final Color MAGENTA   = new Color(255, 0, 255, 255 );
  public static final Color RAYWHITE  = new Color(245, 245, 245, 255 );
}
