/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Image {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    RaylibJNI.Image_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = RaylibJNI.Image_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setWidth(int value) {
    RaylibJNI.Image_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return RaylibJNI.Image_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    RaylibJNI.Image_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return RaylibJNI.Image_height_get(swigCPtr, this);
  }

  public void setMipmaps(int value) {
    RaylibJNI.Image_mipmaps_set(swigCPtr, this, value);
  }

  public int getMipmaps() {
    return RaylibJNI.Image_mipmaps_get(swigCPtr, this);
  }

  public void setFormat(int value) {
    RaylibJNI.Image_format_set(swigCPtr, this, value);
  }

  public int getFormat() {
    return RaylibJNI.Image_format_get(swigCPtr, this);
  }

  public Image() {
    this(RaylibJNI.new_Image(), true);
  }

}
