/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public final class LogType {
  public final static LogType LOG_INFO = new LogType("LOG_INFO", RaylibJNI.LOG_INFO_get());
  public final static LogType LOG_WARNING = new LogType("LOG_WARNING", RaylibJNI.LOG_WARNING_get());
  public final static LogType LOG_ERROR = new LogType("LOG_ERROR", RaylibJNI.LOG_ERROR_get());
  public final static LogType LOG_DEBUG = new LogType("LOG_DEBUG", RaylibJNI.LOG_DEBUG_get());
  public final static LogType LOG_OTHER = new LogType("LOG_OTHER", RaylibJNI.LOG_OTHER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LogType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LogType.class + " with value " + swigValue);
  }

  private LogType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LogType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LogType(String swigName, LogType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LogType[] swigValues = { LOG_INFO, LOG_WARNING, LOG_ERROR, LOG_DEBUG, LOG_OTHER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

