/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class MaterialMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MaterialMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MaterialMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_MaterialMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTexture(Texture2D value) {
    RaylibJNI.MaterialMap_texture_set(swigCPtr, this, Texture2D.getCPtr(value), value);
  }

  public Texture2D getTexture() {
    long cPtr = RaylibJNI.MaterialMap_texture_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Texture2D(cPtr, false);
  }

  public void setColor(Color value) {
    RaylibJNI.MaterialMap_color_set(swigCPtr, this, Color.getCPtr(value), value);
  }

  public Color getColor() {
    long cPtr = RaylibJNI.MaterialMap_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Color(cPtr, false);
  }

  public void setValue(float value) {
    RaylibJNI.MaterialMap_value_set(swigCPtr, this, value);
  }

  public float getValue() {
    return RaylibJNI.MaterialMap_value_get(swigCPtr, this);
  }

  public MaterialMap() {
    this(RaylibJNI.new_MaterialMap(), true);
  }

}
