/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Mesh {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Mesh(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Mesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Mesh(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVertexCount(int value) {
    RaylibJNI.Mesh_vertexCount_set(swigCPtr, this, value);
  }

  public int getVertexCount() {
    return RaylibJNI.Mesh_vertexCount_get(swigCPtr, this);
  }

  public void setTriangleCount(int value) {
    RaylibJNI.Mesh_triangleCount_set(swigCPtr, this, value);
  }

  public int getTriangleCount() {
    return RaylibJNI.Mesh_triangleCount_get(swigCPtr, this);
  }

  public void setVertices(SWIGTYPE_p_float value) {
    RaylibJNI.Mesh_vertices_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getVertices() {
    long cPtr = RaylibJNI.Mesh_vertices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTexcoords(SWIGTYPE_p_float value) {
    RaylibJNI.Mesh_texcoords_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getTexcoords() {
    long cPtr = RaylibJNI.Mesh_texcoords_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTexcoords2(SWIGTYPE_p_float value) {
    RaylibJNI.Mesh_texcoords2_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getTexcoords2() {
    long cPtr = RaylibJNI.Mesh_texcoords2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setNormals(SWIGTYPE_p_float value) {
    RaylibJNI.Mesh_normals_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getNormals() {
    long cPtr = RaylibJNI.Mesh_normals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setTangents(SWIGTYPE_p_float value) {
    RaylibJNI.Mesh_tangents_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getTangents() {
    long cPtr = RaylibJNI.Mesh_tangents_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setColors(SWIGTYPE_p_unsigned_char value) {
    RaylibJNI.Mesh_colors_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getColors() {
    long cPtr = RaylibJNI.Mesh_colors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setIndices(SWIGTYPE_p_unsigned_short value) {
    RaylibJNI.Mesh_indices_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getIndices() {
    long cPtr = RaylibJNI.Mesh_indices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setVaoId(long value) {
    RaylibJNI.Mesh_vaoId_set(swigCPtr, this, value);
  }

  public long getVaoId() {
    return RaylibJNI.Mesh_vaoId_get(swigCPtr, this);
  }

  public void setVboId(SWIGTYPE_p_unsigned_int value) {
    RaylibJNI.Mesh_vboId_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getVboId() {
    long cPtr = RaylibJNI.Mesh_vboId_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public Mesh() {
    this(RaylibJNI.new_Mesh(), true);
  }

}
