/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Model {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Model(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Model obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Model(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMesh(Mesh value) {
    RaylibJNI.Model_mesh_set(swigCPtr, this, Mesh.getCPtr(value), value);
  }

  public Mesh getMesh() {
    long cPtr = RaylibJNI.Model_mesh_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Mesh(cPtr, false);
  }

  public void setTransform(Matrix value) {
    RaylibJNI.Model_transform_set(swigCPtr, this, Matrix.getCPtr(value), value);
  }

  public Matrix getTransform() {
    long cPtr = RaylibJNI.Model_transform_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public void setMaterial(Material value) {
    RaylibJNI.Model_material_set(swigCPtr, this, Material.getCPtr(value), value);
  }

  public Material getMaterial() {
    long cPtr = RaylibJNI.Model_material_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Material(cPtr, false);
  }

  public Model() {
    this(RaylibJNI.new_Model(), true);
  }

}
