/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class RayHitInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RayHitInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RayHitInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_RayHitInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHit(boolean value) {
    RaylibJNI.RayHitInfo_hit_set(swigCPtr, this, value);
  }

  public boolean getHit() {
    return RaylibJNI.RayHitInfo_hit_get(swigCPtr, this);
  }

  public void setDistance(float value) {
    RaylibJNI.RayHitInfo_distance_set(swigCPtr, this, value);
  }

  public float getDistance() {
    return RaylibJNI.RayHitInfo_distance_get(swigCPtr, this);
  }

  public void setPosition(Vector3 value) {
    RaylibJNI.RayHitInfo_position_set(swigCPtr, this, Vector3.getCPtr(value), value);
  }

  public Vector3 getPosition() {
    long cPtr = RaylibJNI.RayHitInfo_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector3(cPtr, false);
  }

  public void setNormal(Vector3 value) {
    RaylibJNI.RayHitInfo_normal_set(swigCPtr, this, Vector3.getCPtr(value), value);
  }

  public Vector3 getNormal() {
    long cPtr = RaylibJNI.RayHitInfo_normal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Vector3(cPtr, false);
  }

  public RayHitInfo() {
    this(RaylibJNI.new_RayHitInfo(), true);
  }

}
