/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Rectangle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Rectangle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Rectangle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Rectangle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    RaylibJNI.Rectangle_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return RaylibJNI.Rectangle_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    RaylibJNI.Rectangle_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return RaylibJNI.Rectangle_y_get(swigCPtr, this);
  }

  public void setWidth(float value) {
    RaylibJNI.Rectangle_width_set(swigCPtr, this, value);
  }

  public float getWidth() {
    return RaylibJNI.Rectangle_width_get(swigCPtr, this);
  }

  public void setHeight(float value) {
    RaylibJNI.Rectangle_height_set(swigCPtr, this, value);
  }

  public float getHeight() {
    return RaylibJNI.Rectangle_height_get(swigCPtr, this);
  }

  public Rectangle() {
    this(RaylibJNI.new_Rectangle(), true);
  }

}
