/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class RenderTexture2D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RenderTexture2D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RenderTexture2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_RenderTexture2D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    RaylibJNI.RenderTexture2D_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return RaylibJNI.RenderTexture2D_id_get(swigCPtr, this);
  }

  public void setTexture(Texture2D value) {
    RaylibJNI.RenderTexture2D_texture_set(swigCPtr, this, Texture2D.getCPtr(value), value);
  }

  public Texture2D getTexture() {
    long cPtr = RaylibJNI.RenderTexture2D_texture_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Texture2D(cPtr, false);
  }

  public void setDepth(Texture2D value) {
    RaylibJNI.RenderTexture2D_depth_set(swigCPtr, this, Texture2D.getCPtr(value), value);
  }

  public Texture2D getDepth() {
    long cPtr = RaylibJNI.RenderTexture2D_depth_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Texture2D(cPtr, false);
  }

  public RenderTexture2D() {
    this(RaylibJNI.new_RenderTexture2D(), true);
  }

}
