/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Shader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Shader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Shader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Shader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    RaylibJNI.Shader_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return RaylibJNI.Shader_id_get(swigCPtr, this);
  }

  public void setLocs(SWIGTYPE_p_int value) {
    RaylibJNI.Shader_locs_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getLocs() {
    long cPtr = RaylibJNI.Shader_locs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public Shader() {
    this(RaylibJNI.new_Shader(), true);
  }

}
