/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public final class TextureWrapMode {
  public final static TextureWrapMode WRAP_REPEAT = new TextureWrapMode("WRAP_REPEAT", RaylibJNI.WRAP_REPEAT_get());
  public final static TextureWrapMode WRAP_CLAMP = new TextureWrapMode("WRAP_CLAMP");
  public final static TextureWrapMode WRAP_MIRROR = new TextureWrapMode("WRAP_MIRROR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextureWrapMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextureWrapMode.class + " with value " + swigValue);
  }

  private TextureWrapMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextureWrapMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextureWrapMode(String swigName, TextureWrapMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextureWrapMode[] swigValues = { WRAP_REPEAT, WRAP_CLAMP, WRAP_MIRROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

