/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Vector3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Vector3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    RaylibJNI.Vector3_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return RaylibJNI.Vector3_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    RaylibJNI.Vector3_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return RaylibJNI.Vector3_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    RaylibJNI.Vector3_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return RaylibJNI.Vector3_z_get(swigCPtr, this);
  }

  public Vector3() {
    this(RaylibJNI.new_Vector3(), true);
  }

  public Vector3(float x, float y, float z) {
    this();
    this.setX(x);
    this.setY(y);
    this.setZ(z);
  }

  public void add_i(Vector3 other) {
    this.setX(this.getX()+other.getX());
    this.setY(this.getY()+other.getY());
    this.setZ(this.getZ()+other.getZ());
  }

  public void add_i(float other) {
    this.setX(this.getX()+other);
    this.setY(this.getY()+other);
    this.setZ(this.getZ()+other);
  }

  public void multiply_i(Vector3 other) {
    this.setX(this.getX()*other.getX());
    this.setY(this.getY()*other.getY());
    this.setZ(this.getZ()*other.getZ());
  }

  public void multiply_i(float other) {
    this.setX(this.getX()*other);
    this.setY(this.getY()*other);
    this.setZ(this.getZ()*other);
  }

  public void subtract_i(Vector3 other) {
    this.setX(this.getX()-other.getX());
    this.setY(this.getY()-other.getY());
    this.setZ(this.getZ()-other.getZ());
  }

  public void subtract_i(float other) {
    this.setX(this.getX()-other);
    this.setY(this.getY()-other);
    this.setZ(this.getZ()-other);
  }

  public Vector3 add(Vector3 other) {
    return new Vector3(
            this.getX()+other.getX(),
            this.getY()+other.getY(),
            this.getZ()+other.getZ()
    );
  }

  public Vector3 add(float other) {
    return new Vector3(
            this.getX()+other,
            this.getY()+other,
            this.getZ()+other);
  }

  public Vector3 multiply(Vector3 other) {
    return new Vector3(
            this.getX()*other.getX(),
            this.getY()*other.getY(),
            this.getZ()*other.getZ());
  }

  public Vector3 multiply(float other) {
    return new Vector3(
            this.getX()*other,
            this.getY()*other,
            this.getZ()*other);
  }

  public Vector3 subtract(Vector3 other) {
    return new Vector3(
            this.getX()-other.getX(),
            this.getY()-other.getY(),
            this.getZ()-other.getZ());
  }

  public Vector3 subtract(float other) {
    return new Vector3(
            this.getX()-other,
            this.getY()-other,
            this.getZ()-other);
  }
}
