/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Vector4 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector4(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Vector4(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    RaylibJNI.Vector4_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return RaylibJNI.Vector4_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    RaylibJNI.Vector4_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return RaylibJNI.Vector4_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    RaylibJNI.Vector4_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return RaylibJNI.Vector4_z_get(swigCPtr, this);
  }

  public void setW(float value) {
    RaylibJNI.Vector4_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return RaylibJNI.Vector4_w_get(swigCPtr, this);
  }

  public Vector4() {
    this(RaylibJNI.new_Vector4(), true);
  }

  public Vector4(float x, float y, float z, float w) {
    this();
    this.setX(x);
    this.setY(y);
    this.setZ(z);
    this.setW(w);
  }
}
