/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Vector3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Vector3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    RaylibJNI.Vector3_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return RaylibJNI.Vector3_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    RaylibJNI.Vector3_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return RaylibJNI.Vector3_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    RaylibJNI.Vector3_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return RaylibJNI.Vector3_z_get(swigCPtr, this);
  }

  public Vector3() {
    this(RaylibJNI.new_Vector3(), true);
  }

  public Vector3(float x, float y, float z) {
    this();
    this.setX(x);
    this.setY(y);
    this.setZ(z);
  }

}
