/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public final class VrDeviceType {
  public final static VrDeviceType HMD_DEFAULT_DEVICE = new VrDeviceType("HMD_DEFAULT_DEVICE", RaylibJNI.HMD_DEFAULT_DEVICE_get());
  public final static VrDeviceType HMD_OCULUS_RIFT_DK2 = new VrDeviceType("HMD_OCULUS_RIFT_DK2");
  public final static VrDeviceType HMD_OCULUS_RIFT_CV1 = new VrDeviceType("HMD_OCULUS_RIFT_CV1");
  public final static VrDeviceType HMD_OCULUS_GO = new VrDeviceType("HMD_OCULUS_GO");
  public final static VrDeviceType HMD_VALVE_HTC_VIVE = new VrDeviceType("HMD_VALVE_HTC_VIVE");
  public final static VrDeviceType HMD_SONY_PSVR = new VrDeviceType("HMD_SONY_PSVR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VrDeviceType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VrDeviceType.class + " with value " + swigValue);
  }

  private VrDeviceType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VrDeviceType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VrDeviceType(String swigName, VrDeviceType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VrDeviceType[] swigValues = { HMD_DEFAULT_DEVICE, HMD_OCULUS_RIFT_DK2, HMD_OCULUS_RIFT_CV1, HMD_OCULUS_GO, HMD_VALVE_HTC_VIVE, HMD_SONY_PSVR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

