/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package raylib;

public class Wave {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Wave(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Wave obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RaylibJNI.delete_Wave(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSampleCount(long value) {
    RaylibJNI.Wave_sampleCount_set(swigCPtr, this, value);
  }

  public long getSampleCount() {
    return RaylibJNI.Wave_sampleCount_get(swigCPtr, this);
  }

  public void setSampleRate(long value) {
    RaylibJNI.Wave_sampleRate_set(swigCPtr, this, value);
  }

  public long getSampleRate() {
    return RaylibJNI.Wave_sampleRate_get(swigCPtr, this);
  }

  public void setSampleSize(long value) {
    RaylibJNI.Wave_sampleSize_set(swigCPtr, this, value);
  }

  public long getSampleSize() {
    return RaylibJNI.Wave_sampleSize_get(swigCPtr, this);
  }

  public void setChannels(long value) {
    RaylibJNI.Wave_channels_set(swigCPtr, this, value);
  }

  public long getChannels() {
    return RaylibJNI.Wave_channels_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_void value) {
    RaylibJNI.Wave_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = RaylibJNI.Wave_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public Wave() {
    this(RaylibJNI.new_Wave(), true);
  }

}
